### ISSUE TITLE
Kerchunk Compatibility 

### ISSUE THREAD

**Issue by peterm790** [DTN-Public/intake-pattern-catalog#14]
Hi, I was really happy to come across this package, it's a much better solution than some hacky code I was using to generate catalogue entries. Thanks for sharing!

My main use case is for kerchunk intake entries which have a slightly different structure to normal intake entries: 

```---
metadata:
  version: 1
sources:
    pattern_test:
        description: Stuff and things
        driver: pattern_cat
        args:
          driver: intake_xarray.xzarr.ZarrSource
          listable: True
          urlpath: "reference://"
          storage_options:
              fo: '/home/pmarsh/ERA5_Kerchunk/references/{step}/{var}.json'
```
Essentially the file path is in `storage options` rather than in the `urlpath`. 

I've got a fork set up to accommodate this here: https://github.com/DTN-Public/intake-pattern-catalog/compare/main...peterm790:intake-pattern-catalog:allow_kerchunk_refs

Let me know if this is something you would like incorporated into main and I'll open up a PR :)

**Comment by raybellwaves** [comment]
yes. PR is welcome
